### PR TITLE
GitHub build pipeline init

### PR DESCRIPTION
**Pull request by TakesTheBiscuit**
GitHub build pipeline init

May need tweaking no promises it'll be perfect

### CODE REVIEW

**Comment by TakesTheBiscuit** [comment]
we will prob need to tweak the branch name dynamically using a github env var/insert

**Comment by Merith-TK** [comment]
Before i will even consider merging this... Squash by hand
Will create a video for you

**Comment by Merith-TK** [comment]
okay steps to compress this
```
backup your local repo 
Make sure the backup is your working branch
BACKUP THE FREAKIN REPO
BACK IT THE F UP
DOUBLE CHECK IT IS YOUR WORKING BRANCH





Okay now that you have a backup. in the backup delete the `.git` folder

Clone the repo again to a different place
checkout the same branch that you are working on.

from master branch, delete your local copy of that branch (instructions online)
And then remake the branch and put the files from your backup in that folder
```

**Comment by TakesTheBiscuit** [comment]
That was a good adventure into gitlab actions.
I'll close the PR and leave the action on the branch we can always pop it into the new space/repo :)

**Comment by TakesTheBiscuit** [comment]
FTR; .github/workflows/main.yml

**Pull request closed without merging**
