### PR TITLE
Adjust T1 bomber price and firing patterns to match FAF balance

### PR DESCRIPTION
**Pull request by Ithilis**
It follow some old pattern, now it cost same and have same rof as other
bombers.

### CODE REVIEW

**Comment by speed2CZ** [comment]
Is it suppose to be "price"?
Also you're not fixing anything, it's not broken, you're just adjusting some values...

**Comment by Ithilis** [comment]
> Is it suppose to be "price"?
> Also you're not fixing anything, it's not broken, you're just adjusting some values...

of course, it was. 
And you are not right, while actually its suppose not to adjust but only add number that follows other bombers pattern, so that is why I name it fix pice :D.

**Comment by Apofenas** [comment]
I'm not quite sure how did this happen again, but i'm pretty sure I adjusted t1 bomber price at least 2 times already and now it does match FAF values again ...

**Comment by Exotic-Retard** [comment]
aaaand PR named properly :D

**Pull request merged**
